name: Log changes to staging

on:
  push:
    branches: [ staging ]
    paths:
      - elana-site/**
  workflow_dispatch:

jobs:
  create-src-log:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
      with:
        ref: staging
        fetch-depth: 0
    
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        base: 'origin/staging'
        ref: ${{ github.sha }}
        filters: |
          src:
            - 'elana-site/src/**'

    - name: Debug
      run: |
        echo "src changes: ${{ steps.filter.outputs.src }}"
        git log -2 --oneline

    - name: update src
      if: steps.filter.outputs.src == 'true'
      run: |
        echo "New content added to /src $(date)" >> ./elana-site/src/log.txt
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add ./elana-site/src/log.txt
        git commit -m "Add log to src"
        git push

  create-public-log:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
      with:
        ref: staging
        fetch-depth: 0
    
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        base: 'origin/staging'
        ref: ${{ github.sha }}
        filters: |
          public:
            - 'elana-site/public/**'

    - name: Debug
      run: |
        echo "public changes: ${{ steps.filter.outputs.public }}"
        git log -2 --oneline

    - name: update public
      if: steps.filter.outputs.public == 'true'
      run: |
        echo "New content added to /public $(date)" >> ./elana-site/public/log.txt
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add ./elana-site/public
        git commit -m "Add log to public"
        git push
