name: Log changes to staging

on:
  push:
    branches: [ staging ]
    paths:
      - elana-site/**
  workflow_dispatch:

jobs:
  create-src-log:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: staging
        fetch-depth: 0

    - name: Get previous commit
      id: get-prev-commit
      run: |
          echo "prev_commit=$(git rev-parse staging~1)" >> $GITHUB_OUTPUT   
    
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        base: ${{ steps.get-prev-commit.outputs.prev_commit }}
        ref: ${{ github.sha }}
        filters: |
          src:
            - 'elana-site/src/**'

    - name: Debug
      run: |
        echo "src changes: ${{ steps.filter.outputs.src }}"
        git log -2 --oneline

    - name: run src step
      if: steps.filter.outputs.src == 'true'
      run: |
        cd elana-site/src
        date      


  create-public-log:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: staging
        fetch-depth: 0
    
    - name: Get previous commit
      id: get-prev-commit
      run: |
          echo "prev_commit=$(git rev-parse staging~1)" >> $GITHUB_OUTPUT

    - uses: dorny/paths-filter@v3
      id: filter
      with:
        base: ${{ steps.get-prev-commit.outputs.prev_commit }}
        ref: ${{ github.sha }}
        filters: |
          public:
            - 'elana-site/public/**'

    - name: Debug
      run: |
        echo "public changes: ${{ steps.filter.outputs.public }}"
        git log -2 --oneline

    - name: update public
      if: steps.filter.outputs.public == 'true'
      run: |
        echo "New content added to /public $(date)" >> ./elana-site/public/log.txt
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add ./elana-site/public
        git commit -m "Add log to public"
        git push

  
  
  
  create-bee-log:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: staging
        fetch-depth: 0
    
    - name: Get previous commit
      id: get-prev-commit
      run: |
          echo "prev_commit=$(git rev-parse staging~1)" >> $GITHUB_OUTPUT   

    - uses: dorny/paths-filter@v3
      id: filter
      with:
        base: ${{ steps.get-prev-commit.outputs.prev_commit }}
        ref: ${{ github.sha }}
        filters: |
          bee:
            - 'elana-site/bee/**'

    - name: Debug
      run: |
        echo "bee changes: ${{ steps.filter.outputs.bee }}"
        git log -2 --oneline

    - name: update bee
      if: steps.filter.outputs.bee == 'true'
      run: |
        echo "New content added to /bee $(date)" >> ./elana-site/bee/log.txt
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add ./elana-site/bee
        git commit -m "Add log to bee"
        git push
