name: Log changes to staging

on:
  push:
    branches: [ staging ]
    paths:
      - elana-site/**
  workflow_dispatch:

jobs:
  create-src-log:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: staging
        fetch-depth: 0

    - name: Get previous commit
      id: get-prev-commit
      run: |
          echo "prev_commit=$(git rev-parse staging~1)" >> $GITHUB_OUTPUT   
    
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        base: ${{ steps.get-prev-commit.outputs.prev_commit }}
        ref: ${{ github.sha }}
        filters: |
          src:
            - 'elana-site/src/**'

    - name: Debug
      run: |
        echo "src changes: ${{ steps.filter.outputs.src }}"
        git log -2 --oneline

    - name: get date of src change
      if: steps.filter.outputs.src == 'true'
      run: |
        cd elana-site/src
        date      


  create-public-log:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: staging
        fetch-depth: 0
    
    - name: Get previous commit
      id: get-prev-commit
      run: |
          echo "prev_commit=$(git rev-parse staging~1)" >> $GITHUB_OUTPUT   

    - uses: dorny/paths-filter@v3
      id: filter
      with:
        base: ${{ steps.get-prev-commit.outputs.prev_commit }}
        ref: ${{ github.sha }}
        filters: |
          public:
            - 'elana-site/public/**'

    - name: Debug
      run: |
        echo "public changes: ${{ steps.filter.outputs.public }}"
        git log -2 --oneline

    - name: get date of public change
      if: steps.filter.outputs.public == 'true'
      run: |
        cd elana-site/public
        date 

  create-lib-log:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: staging
        fetch-depth: 0
    
    - name: Get previous commit
      id: get-prev-commit
      run: |
          echo "prev_commit=$(git rev-parse staging~1)" >> $GITHUB_OUTPUT   

    - uses: dorny/paths-filter@v3
      id: filter
      with:
        base: ${{ steps.get-prev-commit.outputs.prev_commit }}
        ref: ${{ github.sha }}
        filters: |
          lib:
            - 'elana-site/lib/**'

    - name: Debug
      run: |
        echo "lib changes: ${{ steps.filter.outputs.lib }}"
        git log -2 --oneline

    - name: get date of lib change
      if: steps.filter.outputs.lib == 'true'
      run: |
        cd elana-site/lib
        date 

  create-foo-log:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: staging
        fetch-depth: 0
    
    - name: Get previous commit
      id: get-prev-commit
      run: |
          echo "prev_commit=$(git rev-parse staging~1)" >> $GITHUB_OUTPUT   

    - uses: dorny/paths-filter@v3
      id: filter
      with:
        base: ${{ steps.get-prev-commit.outputs.prev_commit }}
        ref: ${{ github.sha }}
        filters: |
          foo:
            - 'elana-site/foo/**'

    - name: Debug
      run: |
        echo "foo changes: ${{ steps.filter.outputs.foo }}"
        git log -2 --oneline

    - name: get date of foo change
      if: steps.filter.outputs.foo == 'true'
      run: |
        cd elana-site/foo
        date 
