name: Log changes to staging

on:
  push:
    branches: [ staging ]
    paths:
      - elana-site/src/**
      - elana-site/public/**
  workflow_dispatch:

jobs:
  create-file:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          src:
          - 'elana-site/src/**'
          public:
          - 'elana-site/public/**'

    - name: update src
      if: steps.changes.outputs.src == 'true'
      run: |
        echo "New content added to /src $(date)" >> ./elana-site/src/log.txt
   
    - name: update public
      if: steps.changes.outputs.public == 'true'
      run: |
        echo "New content added to /public $(date)" >> ./elana-site/public/log.txt
      
    - name: Configure Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Commit file
      run: |
        git add ./elana-site
        git commit -m "Add log"
        git push