name: Log changes to staging

on:
  push:
    branches: [ staging ]
    paths:
      - elana-site/src/**
      - elana-site/public/**
  workflow_dispatch:

jobs:
  create-file:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4

    - name: Debug commit information
      run: |
        echo "Comparing commits:"
        echo "Before: ${{ github.event.before }}"
        echo "After: ${{ github.event.after }}"
        echo "Modified files: ${{ toJSON(github.event.head_commit.modified) }}"
        echo "Added files: ${{ toJSON(github.event.head_commit.added) }}"
        echo "Removed files: ${{ toJSON(github.event.head_commit.removed) }}"
        
    - name: Add log to elana-site/src
      if: |
        contains(toJSON(github.event.head_commit.modified), 'elana-site/src') || 
        contains(toJSON(github.event.head_commit.added), 'elana-site/src') ||
        contains(toJSON(github.event.head_commit.removed), 'elana-site/src')
      run: |
        echo "New content added to /src $(date)" >> ./elana-site/src/log.txt

    - name: Add log to elana-site/public
      if: |
        contains(toJSON(github.event.head_commit.modified), 'elana-site/public') || 
        contains(toJSON(github.event.head_commit.added), 'elana-site/public') ||
        contains(toJSON(github.event.head_commit.removed), 'elana-site/public')
      run: |
        echo "New content added to /public $(date)" >> ./elana-site/public/log.txt
      
    - name: Configure Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Commit file
      run: |
        git add ./elana-site
        git commit -m "Add log"
        git push