name: Create Empty File

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  create-file:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Create empty file
      run: touch empty.txt
      
    - name: Configure Git
      run: |
        git config --global ekelly55 'github-actions[bot]'
        git config --global eamonn.michael.kelly@gmail.com 'github-actions[bot]@users.noreply.github.com'
        
    - name: Commit file
      run: |
        git add empty.txt
        git commit -m "Add empty file"
        git push