name: Build, Zip, and Deploy Lambda

on:
  push:
    branches:
      - main
      - staging
    paths:
      - ./elana-site/**
  workflow_dispatch:

permissions:
  contents: read
  issues: write
  packages: read

jobs:
  build-zip-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: test-run
        run: |
          cd elana-site
          touch test.txt


      - name: Configure Git
        run: |
          git config --global user.ekelly55 'github-actions[bot]'
          git config --global user.eamonn.michael.kelly@gmail.com 'github-actions[bot]@users.noreply.github.com'
        
      - name: Commit file
        run: |
          git add test.txt
          git commit -m "Add empty file"
          git push

